### ISSUE TITLE
mounter.js setPositions sets pos to bottom, must set it according to viewport

### ISSUE THREAD

**Issue by graberzz** [graberzz/it-planeta#13]
@UselessNaughtyCat Повыделяй высокие блоки на сайтах с вертикальным скроллом, наше меню улетает на дно.

**Comment by graberzz** [comment]
@UselessNaughtyCat  ТЕРЬ НАверх улетает, сайт УКСЕВТА:
![image](https://user-images.githubusercontent.com/22579048/37427752-1cf4049c-27ec-11e8-898b-9ee56dbf5b71.png)

**Comment by onemonaughtycat** [comment]
НЕТУ БАГОВ, ЗАКРОЙ ТЕМУ!!!
